englishDictApp/englishDictApp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wordsApp.urls', namespace='dictionaryapp')),
    path('trainer/', include('trainerapp.urls', namespace='trainerapp')),
    path('user/', include('user.urls', namespace='user')),

]

englishDictApp/trainerapp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'trainerapp'

urlpatterns = [
    path('', view=views.construct_trainer_page, name='contruct'),
    path('test/', view=views.trainer_page, name='trainer')

]

englishDictApp/user/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views 

from . import views as view

app_name = 'user'

urlpatterns = [
    path('profile_page/', view=view.profile_page, name='profile'),
    path('register/', view=view.user_registration, name='signup'),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(next_page='user:login'), name="logout"),
    path('email_verify/<uidb64>/<token>/', view=view.email_verify, name='email_verify'),
]

englishDictApp/wordsApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'dictionaryapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:category>/', views.category_page, name='category'),
    path('dictionary/', views.dictionary_list, name='dictionary_list'),
    path('add/', views.add_to_fav, name='fav'),
    path('rmfav/', views.rm_from_fav, name='fav_del'),
    path('add_word/', views.add_word, name='add_word'),
    path('word/<int:pk>/', views.word_page, name='word_page')
    
]

englishDictApp/templates/addwordform.html
{% extends "base.html" %}
{% block content %}
<div class="form-block">
    <form class="form-container" action="{% url 'dictionaryapp:add_word' %}" method="POST">
        {% csrf_token %}
        <div class="fieldWrapper">
            <div class="" style="color: red;">{{form.eng_version.errors}}</div>
            <div class="input-labels">
                {{ form.eng_version.label_tag }}
                {{ form.eng_version }}
            </div>
            <div class="" style="color: red;">{{form.rus_version.errors}}</div>
            <div class="input-labels">
                {{ form.rus_version.label_tag }}
                {{ form.rus_version }}
            </div>
        </div>
        <div class="categories">
            <div class="" style="color: red;">{{form.category.errors}}</div>
            <div class="category-block">
                <div class="">Select category:</div>
            </div>
            {% for category in form.category.field.queryset %}
                <label for="category_{{ category.pk }}">
                    <input type="checkbox" id="category_{{ category.pk }}" name="category" value="{{ category.pk }}">
                    {{ category.name }}
                </label>
            {% endfor %}
        </div>

        <div class="button-send">
            <button type="submit">Save</button>
        </div>
    </form>
</div>

{% endblock %}

englishDictApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <header class="header">
        <div class="left">
          <a href="{% url 'dictionaryapp:index' %}">Category</a>
          <a href="{% url 'dictionaryapp:dictionary_list' %}">Dictionary</a>
          <a href="{% url 'dictionaryapp:add_word' %}">Add word </a>
          
        </div>
        <div class="right">
            {% if request.user.is_authenticated %}
                <a href="{% url 'user:profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'user:login' %}">Sign In</a>
            {% endif %}
        </div>
      </header>
    <div class="main-content">
    {% block content%}
    {% endblock %}
    </div>
</body>
</html>

englishDictApp/templates/category.html
{% extends 'base.html' %}
      {%block content %}
            {% if words %}
            <form action="{% url 'dictionaryapp:fav' %}" method="POST">
                  {% csrf_token %}
                  <div class="button-send"><button class='save' type="submit">Save</button></div>
                  <input type="hidden" name="category" value="{{category}}">
                        {% for word in words %}
                        <div class="translate-block">
                              <label><a href="{% url 'dictionaryapp:word_page' word.id %}">{{word.eng_word}}</a> - {{word.ru_word}}</label>
                              <input type="checkbox" class="myCheckbox" data-id="1" name="words", value="{{word.id}}" {% if word.is_favorite %}checked{% endif %}>
                        </div>
                        {%endfor%}
            </form>
            {% else %}
            <h1>Category is empty</h1>
            {% endif %}
      {%endblock%}

englishDictApp/templates/construct_trainer.html
{% extends 'base.html' %}
{%block content %}
<form action="{%url 'trainerapp:trainer' %}" method="GET">
      {{form}}
      <button type="submit">Create</button>
</form> 

{%endblock%}

englishDictApp/templates/dict.html
{% extends 'base.html' %}
{%block content%}
    <div class="main">
        <div class="dictionary-container">
            {% for letter, words in letter_dict.items %}
                <div class="letter-container">
                    <div class="dictionary-headers">
                        <h3>{{ letter }}</h3>
                    </div>
                    <div class="words-list">
                        <div class="words-list-column1">
                            <ul>
                                {% for word in words|slice:"::2" %}  
                                    <li><a href="{%url 'dictionaryapp:word_page' word.id %}">{{ word.eng_word }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="words-list-column2">
                            <ul>
                                {% for word in words|slice:"1::2" %}  
                                    <li><a href="{% url 'dictionaryapp:word_page' word.id %}">{{ word.eng_word }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{%endblock%}

englishDictApp/templates/index.html
{% extends "base.html" %}
{%block content%}
<div class="content">
    <div class="container-ul">
        <ul>
{% for category in categories %}
        <li class="li-index">
            <a href="{% url 'dictionaryapp:category' category.slug %}">{{category.name}}</a>
        </li>
{%endfor%}
</ul>
</div>
</div>
{% endblock %}

englishDictApp/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<h1>Dictionary List</h1>
<div class="information-block">
    <div><strong>Email:</strong> {{ profile.user.email }}</div>
    <div><strong>Usermail:</strong> {{ profile.user.username }}</div>
    <div><strong>Your level:</strong> {{ profile.user_level }}</div>
    <div><strong>Dictionary count:</strong> {{ words_list.count }}</div>
    <form action="{% url 'user:logout' %}" method="POST">
      {% csrf_token %}
      <div class="button-send"><button class="delete" type="submit">Logout</button></div>
  </form>
</div>
<a href="{% url 'trainerapp:contruct' %}" method="GET" class="construct-trainer-block">Test yourself</a>
<div class="content">
    {% if words_list %}
    <form action="{% url 'dictionaryapp:fav_del' %}" method="POST">
        {% csrf_token %}
        {% for word in words_list %}
        <div class="translate-block">
            <label>{{ word.word.eng_word.word }} - {{ word.word.ru_word.word }}</label>
            <input type="checkbox" class="myCheckbox" name="words" value="{{ word.id }}">
        </div>
        {% endfor %}
        <div class="button-send"><button class="delete" type="submit">Delete selected</button></div>
    </form>
    {% else %}
    <p>Dictionary is empty</p>
    {% endif %}
</div>
{% endblock %}

englishDictApp/templates/result_page.html
{% extends 'base.html' %}
      {%block content %}
      <h1>Title</h1>
      {% for answer in answer_list%}
      <div class="form-container">
        <div class="rus-veriosn">
          {{answer.form.rus_version.value}}
        </div>
        <div class="eng-answer">
          <input disabled value="{{answer.form.eng_version.value}}">
        </div>
        <div class="answers_status" style="{% if answer.answers_status%} color: green {% else %} color: red {%endif%}">
          {{answer.answers_status}}
        </div>
        <div class="original_answer" style="text-decoration: underline;">
          <a href="{% url 'dictionaryapp:word_page' answer.original_answer.id %}">
            {{answer.original_answer.eng_word}}
          </a>
        </div>
      </div>
      {%endfor%}
      </form>
        {%endblock%}

englishDictApp/templates/trainer_page.html
{% extends 'base.html' %}
      {%block content %}
      <h1>Title</h1>
      <form method="POST" action="{% url 'trainerapp:trainer' %}">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset%}
      <div class="form-container">
        <div hidden>
          {{form.rus_version}}
          {{form.id}}
        </div>
        {{form.rus_version.value}}
        {{form.eng_version}}
      </div>
      {%endfor%}
      <button type="submit">Отправить</button>
      </form>
        {%endblock%}

englishDictApp/templates/trans_page.html
{% extends "base.html" %}
{%block content%}
<div class="word_profile">
            <h1 class="word-title"> {{word.eng_word}} ({{word.eng_word.id}})</h1>
    <p> All translates</p>
    <form action="{% url 'dictionaryapp:fav' %}" method="POST">
        {% csrf_token %}
    <ul class="ul-translate-container">
        {% for translate in all_translates%}
        <li class="li-translate-container">
            {{translate.ru_word.word}}
            <input type="hidden" name="category" value="{{translate.category}}">
            <input type="checkbox" class="myCheckbox" data-id="1" name="words", value="{{translate.id}}"
            {% if translate.id in fav_list %}checked{% endif %}>
            <div class="category-link">
                {% for category in translate.category.all %}
                <a href="{% url 'dictionaryapp:category' category.slug %}">@{{category}}</a>
                {% endfor %}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="button-send"><button type="submit">Save</button></div>
</form>
</div>

{% endblock %}`

englishDictApp/templates/word_page.html
{% extends 'base.html' %}
{% block content %}
<div class="word_profile">
        <form action="{% url 'dictionaryapp:fav' %}" method="POST">
            {% csrf_token %}
            <h1 class="word-title"> {{word.eng_word}} ({{word.id}}) 
            <input type="checkbox" class="myCheckbox" data-id="1" name="words", value="{{word.id}}"
            {% if word.id in fav_list %}checked{% endif %}>
            <div class="button-send"><button type="submit">Save</button></div>
        </form>
    </h1>
    <ul>
        {%for ru_word in ru_words %}
        <li>
            {{ru_word}}
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}